# Generated by Django 6.0.4 on 2026-04-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_model', models.CharField(max_length=100)),
                ('breaking', models.TextField()),
                ('location', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('file', models.ImageField(blank=True, null=True, upload_to='orders/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
