# Generated by Django 6.0.4 on 2026-04-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='breaking',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.ImageField(default=' ', upload_to='orders/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
