# Generated by Django 5.0.4 on 2026-05-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_order_user_alter_order_file_alter_order_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/'),
        ),
    ]
